<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>16-Promise - Static Method - all</title>
  </head>
  <body>
    <script>
      const p1 = new Promise((resolve, reject) => {
        setTimeout(function () {
          resolve("p1 is done.");
        }, 1000);
      });

      // p1.then((data) => {
      //   console.log(data);
      // });

      const p2 = new Promise((resolve, reject) => {
        setTimeout(function () {
          resolve("p2 is done.");
        }, 2000);
      });

      // p2.then((data) => {
      //   console.log(data);
      // });
      const p3 = new Promise((resolve, reject) => {
        setTimeout(function () {
          resolve("p3 is done.");
        }, 3000);
      });

      // p3.then((data) => {
      //   console.log(data);
      // });
      const p4 = new Promise((resolve, reject) => {
        setTimeout(function () {
          reject("p4 is rejected.");
        }, 1500);
      });

      // p4.catch((err) => {
      //   console.log(err);
      // });
      //   const p1 = Promise.resolve("p1 Success");

      //   p1.then((data) => {
      //     console.log(data); // p1 Success
      //   });

      // Common Mistake:
      //   const p1 = Promise.resolve("p1 Success").then((data) => {
      //     console.log(data); // p1 Success
      //     // return a fulfilled promise with undefined.
      //   });

      //   p1.then((data) => {
      //     console.log(data); // undefined - this is why we get undefined here instead of p1 Success.
      //   });

      // When all p1, p2 & p3 are fulfilled, then the PromiseState is fulfilled.
      Promise.all([p1, p2, p3])
        .then((data) => {
          console.log(data); // ['p1 is done.', 'p2 is done.', 'p3 is done.']
        })
        .catch((err) => {
          console.log(err);
        });

      // When one of the promise instance are rejected, then the PromiseState is rejected.
      Promise.all([p1, p2, p3, p4])
        .then((data) => {
          console.log(data);
        })
        .catch((err) => {
          console.log(err); // p4 is rejected.
        });

      //   const p = Promise.all([p1, p2, p3, p4]);
      //   console.log(p);
      //   p.catch(() => {
      //     console.log("hello");
      //   });
    </script>
  </body>
</html>
